### ISSUE TITLE
Detect if a window needs server-side decorations

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#154]
Not sure if I'm missing something, but there doesn't seem to be a way to detect if a window requires server-side decorations.

**Comment by plfiorini** [comment]
Nope currently there's no way to do that.
This involves some kind of protocol between applications and compositors but I don't seen any protocol like this in the official ones. Something like this was proposed in the Wayland mailing list once but didn't have much success.

**Comment by iBeliever** [comment]
Hmm, that's unfortunate. How do you plan to handle this in Hawaii?

**Comment by plfiorini** [comment]
Considering only the following three kind of clients: Qt, Gtk+ and XWayland we have the following situation:
* Qt: has CSD by default (due to limitations in the current implmentation some platforms might not be able to draw decorations) and you can make plugins though you can disable CSD with an env variable.
* Gtk+: CSD only. You can do tricks with the styles to wipe off the border or the compositor can know what is actual window geometry (that is the whole window geometry without decorations) with the xdg-shell protocol but the header bar will still react to events.
* XWayland: SSD mostly, but depends on the application. Guess that Gtk+ clients will have CSD.

Until someone will try again to get said protocol in and get applications to use it, I plan to determine disable Qt decorations and draw SSD only for clients without the xdg-shell window geometry this way CSD will be done only for Wayland Gtk+ clients. X11 Gtk+ clients will probably get both though but I'm not worried since most if not all of them run on Wayland just fine.

**Comment by iBeliever** [comment]
Thanks @plfiorini, that's helpful.

Also, here's an article about server-side decorations in KWin: http://blog.martin-graesslin.com/blog/2015/12/server-side-decorations-coming-to-kwinwayland/. Looks like they plan on submitting a protocol for this to Wayland next year, so hopefully that works out.

**Comment by plfiorini** [comment]
Yep that was the idea suggested by Martin on the ML.
Hope that the idea will be re-evaluated this time. Though Gtk+ will still likely be always CSD. Which is not a problem except for visual consistency.
