### ISSUE TITLE
Add support for Qt 5.8

### ISSUE THREAD

**Issue by tpgxyz** [greenisland/greenisland#231]
Hi,
Qt5PlatformSupport got splitted into Qt5FontDatabaseSupport, Qt5ThemeSupport and Qt5EventDispatcherSupport

Would be nice to have it adapted.

**Comment by demmm** [comment]
Maybe this commit is helpful for the new way:
https://codereview.qt-project.org/#/c/172485/

**Comment by abucodonosor** [comment]
Does this fix it ? ( note is not even compile tested on qt 5.8.0 since I don't have qt 5.8.0 around)

http://sigsegv.spdns.eu/~crazy/qt-5.8.x-test.patch

**Comment by plfiorini** [comment]
@tpgxyz Sorry for the delay. We merged Hawaii and Papyros together recently in order to have a larger team: https://liri.io/blog/2017/01/01/welcome-to-liri.html

Upcoming Liri OS 0.10.0 will support Qt 5.8. Green Island has been moved to the new org as well under the name [liri-wayland][https://github.com/lirios/wayland].

I'm beginning to branch the code for 0.10.0 now.
