### ISSUE TITLE
Green Island crashes on startup

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#55]
I'm using Qt 5.5 and the custom version of Qt Wayland (compiled from the AUR package, with the `output55` branch). When I run Green Island, I get:

    $ greenisland
    greenisland: symbol lookup error: /usr/local/lib64/libGreenIsland.so.0: undefined symbol: _ZN23QWaylandQuickCompositor16staticMetaObjectE

**Comment by plfiorini** [comment]
Looks like a linker issue rather than a crash.
Could you try rebuilding greenisland, I suspect that it was previously built with an older qtwayland copy.

**Comment by plfiorini** [comment]
BTW I just force pushed output55 could you rebuild that before greenisland?

**Comment by iBeliever** [comment]
Green Island still fails to start with the same linker error, even after trying the latest qtwayland version from `output55`. Does the error have anything to do with QWaylandQuickCompositor not having a QObject root?

I'm going to try doing a fresh install of qtbase off of the `dev` branch to see if there were any recent changes that might affect this.

**Comment by iBeliever** [comment]
Ok, I've done a full rebuild of qt5-base-git, qt5-declarative-git, and hawaii-qt5-wayland-git (all of Qt 5.5, not 5.4), and then rebuilt greenisland. I still get the same linker error on startup.

**Comment by iBeliever** [comment]
I realized that the original compositor for Papyros has a very similar signature:

    class QmlCompositor : public QQuickView, public QWaylandQuickCompositor

Compared to Green Island's `Compositor` class:

    class GREENISLAND_EXPORT Compositor : public QObject, public QWaylandQuickCompositor

So something is different in Green Island or your development version of QtWayland since it works fine in Papyros shell with the standard QtWayland 5.5.

**Comment by plfiorini** [comment]
They are different, you inherit from QQuickView because that's the old way of doing it since only one output was supported but anyway you somehow implicitely inherited from QObject anyway since QQuickView inherits from that. With Green Island I need to explicitely inherit from QObject to use signals.
The actual output is rendered on OutputWindow.
BTW, multi output support comes in two patches: the first big chunk is now merged with qtwayland dev, the second one is going to.

**Comment by plfiorini** [comment]
Since you may have previously built qtwayland yourself it might be that you still have some old binaries around.
The thing is: one links to libQt5Compositor.so.5 but this is a symlink to libQt5Compositor.so.5.6.0, previous version had it called libQt5Compositor.so.5.5.0 so maybe greenisland was built with the latter.

When building a new qtwayland version I always make sure I don't have things around and zap the relevant files. My setup has Qt 5.5 installed on /opt/qt5 so I do:

rm -f /opt/qt5/lib/libQt5Compositor*
rm -f /opt/qt5/lib/libQt5WaylandClient*
rm -fr /opt/qt5/lib/cmake/Qt5Compositor
rm -fr /opt/qt5/lib/cmake/Qt5WaylandClient
rm -fr /opt/qt5/include/Qt{Compositor,WaylandClient}

**Comment by iBeliever** [comment]
Ok, I finally figured it out. Qt 5 wasn't the issue - my installation of Green Island was. Apparently I had a left-over install in /usr/local, so removing that fixed the issue. Thanks for your help!

Now, time to start exploring using Green Island for Papyros :)

**Comment by plfiorini** [comment]
Yeaaah \o/
Just make sure you give Green Island and Hawaii publicity.
Also, I have a lot of stuff on my todo list we can work togethe, such as: a way to configure the screen, server side decorations, proper keybindings, keyboard settings, mouse settings to name a few.
